# Using  Yelp API calls

In [1]:
import json

In [2]:
with open('/Users/vinosraj/.secret/yelp_api.json') as f: #change the path to match YOUR path!!
    login = json.load(f)
login.keys()

dict_keys(['client-id', 'api-key'])

In [3]:
from yelpapi import YelpAPI
yelp_api = YelpAPI(login['api-key'], timeout_s=5.0)
yelp_api

In [4]:
# results search
search_results = yelp_api.search_query(location='Rochester, MN',
                                       term='food')
type(search_results)
search_results.keys()

dict_keys(['businesses', 'total', 'region'])

In [5]:
search_results['total']

385

In [8]:
import pandas as pd

In [10]:
biz = pd.DataFrame(search_results['businesses'])
biz.head(3)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,_whFYWHM8V8MmBIU8j74uw,first-meeting-noodle-rochester,First Meeting Noodle,https://s3-media4.fl.yelpcdn.com/bphoto/CSa813...,False,https://www.yelp.com/biz/first-meeting-noodle-...,41,"[{'alias': 'chinese', 'title': 'Chinese'}, {'a...",4.5,"{'latitude': 44.00032, 'longitude': -92.47514}",[],$$,"{'address1': '793 16th St SW', 'address2': 'St...",+15073226002,(507) 322-6002,1873.003211
1,4Z9AZ9H8Zmejxholne7Xzw,yum-poké-rochester,Yum! Poké,https://s3-media4.fl.yelpcdn.com/bphoto/DXzJTF...,False,https://www.yelp.com/biz/yum-pok%C3%A9-rochest...,37,"[{'alias': 'poke', 'title': 'Poke'}]",4.5,"{'latitude': 44.02375, 'longitude': -92.46774}","[delivery, pickup]",NaN,"{'address1': '9 3rd Ave NW', 'address2': 'Ste ...",+15072064969,(507) 206-4969,1183.596034
2,ZrxCgL2VDAO7bbnmo-sJTQ,workshop-food-hall-and-bar-rochester,Workshop Food Hall & Bar,https://s3-media1.fl.yelpcdn.com/bphoto/7u4XYz...,False,https://www.yelp.com/biz/workshop-food-hall-an...,11,"[{'alias': 'bars', 'title': 'Bars'}, {'alias':...",4.5,"{'latitude': 44.00559, 'longitude': -92.45829}",[],NaN,"{'address1': '1232 3rd Ave SE', 'address2': ''...",,,2072.502979

In [11]:
#adding an offset of 20
search_results = yelp_api.search_query(location='Rochester, MN',
                                       term='food',
                                      offset = 20)

In [12]:
search_results['total']

385

In [13]:
biz20 = pd.DataFrame(search_results['businesses'])
biz20.head(3)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,SwHX2EUa7B4uyuTg5DMtAg,the-half-barrel-rochester-2,The Half Barrel,https://s3-media3.fl.yelpcdn.com/bphoto/awX4WW...,False,https://www.yelp.com/biz/the-half-barrel-roche...,254,"[{'alias': 'lounges', 'title': 'Lounges'}, {'a...",4.0,"{'latitude': 44.02021, 'longitude': -92.46417}",[delivery],$$,"{'address1': '304 1st Ave SW', 'address2': '',...",+15072586606,(507) 258-6606,1218.729774
1,v6C2sOxCFUGTFqcBv6FwjQ,hot-chip-burger-bar-rochester,Hot Chip Burger Bar,https://s3-media4.fl.yelpcdn.com/bphoto/Pv-2rT...,False,https://www.yelp.com/biz/hot-chip-burger-bar-r...,105,"[{'alias': 'burgers', 'title': 'Burgers'}, {'a...",4.0,"{'latitude': 44.000288071467, 'longitude': -92...","[delivery, pickup]",$$,"{'address1': '1190 16th St SW', 'address2': ''...",+15074240080,(507) 424-0080,1854.838058
2,MLjDJR4N-h_6_LBJwnHyLQ,ichi-tokyo-rochester,Ichi Tokyo,https://s3-media4.fl.yelpcdn.com/bphoto/jVMnFE...,False,https://www.yelp.com/biz/ichi-tokyo-rochester?...,168,"[{'alias': 'japanese', 'title': 'Japanese'}, {...",4.0,"{'latitude': 43.9923896789551, 'longitude': -9...","[delivery, pickup]",$$,"{'address1': '102 20th St SE', 'address2': 'St...",+15072882577,(507) 288-2577,3048.998621

In [14]:
biz.head(3)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,_whFYWHM8V8MmBIU8j74uw,first-meeting-noodle-rochester,First Meeting Noodle,https://s3-media4.fl.yelpcdn.com/bphoto/CSa813...,False,https://www.yelp.com/biz/first-meeting-noodle-...,41,"[{'alias': 'chinese', 'title': 'Chinese'}, {'a...",4.5,"{'latitude': 44.00032, 'longitude': -92.47514}",[],$$,"{'address1': '793 16th St SW', 'address2': 'St...",+15073226002,(507) 322-6002,1873.003211
1,4Z9AZ9H8Zmejxholne7Xzw,yum-poké-rochester,Yum! Poké,https://s3-media4.fl.yelpcdn.com/bphoto/DXzJTF...,False,https://www.yelp.com/biz/yum-pok%C3%A9-rochest...,37,"[{'alias': 'poke', 'title': 'Poke'}]",4.5,"{'latitude': 44.02375, 'longitude': -92.46774}","[delivery, pickup]",NaN,"{'address1': '9 3rd Ave NW', 'address2': 'Ste ...",+15072064969,(507) 206-4969,1183.596034
2,ZrxCgL2VDAO7bbnmo-sJTQ,workshop-food-hall-and-bar-rochester,Workshop Food Hall & Bar,https://s3-media1.fl.yelpcdn.com/bphoto/7u4XYz...,False,https://www.yelp.com/biz/workshop-food-hall-an...,11,"[{'alias': 'bars', 'title': 'Bars'}, {'alias':...",4.5,"{'latitude': 44.00559, 'longitude': -92.45829}",[],NaN,"{'address1': '1232 3rd Ave SE', 'address2': ''...",,,2072.502979

In [15]:
#concatenate the last two results

businesses = pd.concat([biz,biz20],
                      ignore_index= True)

display(businesses.head(3),businesses.tail(3))

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,_whFYWHM8V8MmBIU8j74uw,first-meeting-noodle-rochester,First Meeting Noodle,https://s3-media4.fl.yelpcdn.com/bphoto/CSa813...,False,https://www.yelp.com/biz/first-meeting-noodle-...,41,"[{'alias': 'chinese', 'title': 'Chinese'}, {'a...",4.5,"{'latitude': 44.00032, 'longitude': -92.47514}",[],$$,"{'address1': '793 16th St SW', 'address2': 'St...",+15073226002,(507) 322-6002,1873.003211
1,4Z9AZ9H8Zmejxholne7Xzw,yum-poké-rochester,Yum! Poké,https://s3-media4.fl.yelpcdn.com/bphoto/DXzJTF...,False,https://www.yelp.com/biz/yum-pok%C3%A9-rochest...,37,"[{'alias': 'poke', 'title': 'Poke'}]",4.5,"{'latitude': 44.02375, 'longitude': -92.46774}","[delivery, pickup]",NaN,"{'address1': '9 3rd Ave NW', 'address2': 'Ste ...",+15072064969,(507) 206-4969,1183.596034
2,ZrxCgL2VDAO7bbnmo-sJTQ,workshop-food-hall-and-bar-rochester,Workshop Food Hall & Bar,https://s3-media1.fl.yelpcdn.com/bphoto/7u4XYz...,False,https://www.yelp.com/biz/workshop-food-hall-an...,11,"[{'alias': 'bars', 'title': 'Bars'}, {'alias':...",4.5,"{'latitude': 44.00559, 'longitude': -92.45829}",[],NaN,"{'address1': '1232 3rd Ave SE', 'address2': ''...",,,2072.502979

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
37,bhXuY0Q4MSosnb04C75ktg,potbelly-sandwich-shop-rochester,Potbelly Sandwich Shop,https://s3-media1.fl.yelpcdn.com/bphoto/ik7nW9...,False,https://www.yelp.com/biz/potbelly-sandwich-sho...,36,"[{'alias': 'salad', 'title': 'Salad'}, {'alias...",3.5,"{'latitude': 44.019931626551326, 'longitude': ...","[delivery, pickup]",$,"{'address1': '318 1st Ave SW', 'address2': '',...",+15074241661,(507) 424-1661,1210.200969
38,Wam7L5OEEAJHv6DmQFeIfg,newts-rochester-7,Newt's,https://s3-media2.fl.yelpcdn.com/bphoto/qSdLzZ...,False,https://www.yelp.com/biz/newts-rochester-7?adj...,274,"[{'alias': 'burgers', 'title': 'Burgers'}, {'a...",4.0,"{'latitude': 44.0209629976761, 'longitude': -9...",[delivery],$$,"{'address1': '216 1/2 1st Ave SW', 'address2':...",+15072890577,(507) 289-0577,1254.368234
39,gRcovn_7MCiRLAgy28iGGQ,the-hyderabad-indian-grill-rochester-2,The Hyderabad indian Grill,https://s3-media2.fl.yelpcdn.com/bphoto/xRaO5n...,False,https://www.yelp.com/biz/the-hyderabad-indian-...,51,"[{'alias': 'indpak', 'title': 'Indian'}]",4.0,"{'latitude': 44.07760333, 'longitude': -92.516...","[delivery, pickup]",NaN,"{'address1': '3462 55th St NW', 'address2': 'S...",+15072066777,(507) 206-6777,7356.749670

In [ ]:
businesses